routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cuy', 'HomeController@cuy')->name('cuy');

Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'contacts'], function () {
        Route::group(['prefix' => 'groups'], function () {
            Route::get('/', 'GroupContactController@index')->name('list-group-contact');
            Route::post('/', 'GroupContactController@store')->name('save-group-contact');
            Route::put('/', 'GroupContactController@update')->name('update-group-contact');
            Route::get('/{id}/delete/', 'GroupContactController@destroy')->name('delete-group-contact');
        });

        Route::get('/', 'ContactController@index')->name('list-contact');
        Route::get('/create', 'ContactController@create')->name('create-contact');
        Route::post('/', 'ContactController@store')->name('save-contact');
        Route::get('/{id}', 'ContactController@edit')->name('edit-contact');
        Route::put('/', 'ContactController@update')->name('update-contact');
        Route::get('/{id}/delete/', 'ContactController@destroy')->name('delete-contact');
    });

    Route::group(['prefix' => 'template-email'], function () {
        Route::get('/', 'EmailBlastController@index')->name('list-template');
        Route::get('/create', 'EmailBlastController@create')->name('create-template');
        Route::get('/{id}', 'EmailBlastController@show')->name('show-template');
        Route::post('/', 'EmailBlastController@store')->name('save-template');
        Route::put('/', 'EmailBlastController@update')->name('update-template');
        Route::get('/{id}/delete/', 'EmailBlastController@destroy')->name('delete-template');
    });

    Route::group(['prefix' => 'job-send-email'], function () {
        Route::get('/', 'JobBlastController@index')->name('list-job');
        Route::get('/create', 'JobBlastController@create')->name('create-job');
        Route::get('/{id}', 'JobBlastController@show')->name('show-job');
        Route::post('/', 'JobBlastController@store')->name('save-job');
        Route::put('/', 'JobBlastController@update')->name('update-jon');
        Route::get('/{id}/delete/', 'JobBlastController@destroy')->name('delete-job');

        Route::get('/{id}/resend', 'JobBlastController@resend')->name('resend-job');

    });

    Route::resource('config-email', 'ConfigEmailController');

    Route::get('/oauth/gmail/callback', function (){
        LaravelGmail::makeToken();
        return redirect()->to('/');
    });

    Route::group(['prefix' => 'gmail'], function () {

        Route::get('/login', function (){
            return LaravelGmail::redirect();
        })->name('gmail.login');

        Route::get('/logout', function (){
            LaravelGmail::logout(); //It returns exception if fails
            return redirect()->to('/home');
        })->name('gmail.logout');
                
        Route::get('/inbox', function () {
            // dd(request());
            $messages = LaravelGmail::message()->unread()->preload()->all();
            echo '<ul>';
            foreach ( $messages as $message ) {
                $body = $message->getHtmlBody();
                echo '<li>' . $subject = $message->getSubject() . '</li>';
            }
            echo '</ul>';
        })->name('gmail.inbox');

        Route::get('/compose', 'HomeController@composeGmail');
    
    });


});

// Route::get('/tes-mail', 'BlastEmailController@index');

// Route::get('/email', 'BlastEmailController@index');


// Route::get('/load-csv', 'BlastEmailController@loadCsv');

app/ConfigEmail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ConfigEmail extends Model
{
    protected $fillable = [
        'name',
        'mail_host',
        'mail_port',
        'mail_username',
        'mail_password',
        'mail_from_address',
        'mail_from_name',
    ];
}

app/Http/Controllers/ConfigEmailController.php
<?php

namespace App\Http\Controllers;

use App\ConfigEmail;
use Illuminate\Http\Request;

class ConfigEmailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('config-emails.index', [
            'configEmails' => ConfigEmail::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ConfigEmail::create($request->all());
        return back()->with('success', 'Item created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ConfigEmail  $configEmail
     * @return \Illuminate\Http\Response
     */
    public function show(ConfigEmail $configEmail)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ConfigEmail  $configEmail
     * @return \Illuminate\Http\Response
     */
    public function edit(ConfigEmail $configEmail)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ConfigEmail  $configEmail
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ConfigEmail $configEmail)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ConfigEmail  $configEmail
     * @return \Illuminate\Http\Response
     */
    public function destroy(ConfigEmail $configEmail, $id)
    {
        dd($id);
    }
}

resources/views/config-emails/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Config Email
                    <button class="btn btn-primary btn-sm float-right" data-toggle="modal" data-target="#add-group">Add</button>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table table-hover table-bordered table-responsive">
                        <thead>
                            <tr>
                                <th> name </th>
                                <th> mail_host </th>
                                <th> mail_port </th>
                                <th> mail_username </th>
                                <th> mail_password </th>
                                <th> mail_from_address </th>
                                <th> mail_from_name </th>
                                {{-- <th>Action</th> --}}
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($configEmails as $item)
                                <tr>
                                    <td> {{ $item->name }} </td>
                                    <td> {{ $item->mail_host }} </td>
                                    <td> {{ $item->mail_port }} </td>
                                    <td> {{ $item->mail_username }} </td>
                                    <td> {{ $item->mail_password }} </td>
                                    <td> {{ $item->mail_from_address }} </td>
                                    <td> {{ $item->mail_from_name }} </td>
                                    {{-- <td>
                                        <a class="btn btn-danger btn-sm" href="{{ route('config-email.destroy', [ $item->id ]) }}" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                                    </td> --}}
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="add-group" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Config</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('config-email.store') }}" method="post">
            @csrf
            <div class="modal-body">

                <div class="form-group">
                    <label for="">name</label>
                    <input required class="form-control" name="name" value="{{ old('name') }}">
                </div>
                <div class="form-group">
                    <label for="">mail_host</label>
                    <input required class="form-control" name="mail_host" value="{{ old('email_host') }}">
                </div>
                <div class="form-group">
                    <label for="">email_port</label>
                    <input required class="form-control" name="mail_port" value="{{ old('email_port') }}">
                </div>
                <div class="form-group">
                    <label for="">mail_username</label>
                    <input required class="form-control" name="mail_username" value="{{ old('email_username') }}">
                </div>
                <div class="form-group">
                    <label for="">mail_password</label>
                    <input required class="form-control" name="mail_password" value="{{ old('email_password') }}">
                </div>
                <div class="form-group">
                    <label for="">mail_from_address</label>
                    <input required class="form-control" name="mail_from_address" value="{{ old('email_from_address') }}">
                </div>
                <div class="form-group">
                    <label for="">mail_from_name</label>
                    <input required class="form-control" name="mail_from_name" value="{{ old('email_from_name') }}">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>

      </div>
    </div>
  </div>
@endsection