routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cuy', 'HomeController@cuy')->name('cuy');

Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'contacts'], function () {
        Route::group(['prefix' => 'groups'], function () {
            Route::get('/', 'GroupContactController@index')->name('list-group-contact');
            Route::post('/', 'GroupContactController@store')->name('save-group-contact');
            Route::put('/', 'GroupContactController@update')->name('update-group-contact');
            Route::get('/{id}/delete/', 'GroupContactController@destroy')->name('delete-group-contact');
        });

        Route::get('/', 'ContactController@index')->name('list-contact');
        Route::get('/create', 'ContactController@create')->name('create-contact');
        Route::post('/', 'ContactController@store')->name('save-contact');
        Route::get('/{id}', 'ContactController@edit')->name('edit-contact');
        Route::put('/', 'ContactController@update')->name('update-contact');
        Route::get('/{id}/delete/', 'ContactController@destroy')->name('delete-contact');
    });

    Route::group(['prefix' => 'template-email'], function () {
        Route::get('/', 'EmailBlastController@index')->name('list-template');
        Route::get('/create', 'EmailBlastController@create')->name('create-template');
        Route::get('/{id}', 'EmailBlastController@show')->name('show-template');
        Route::post('/', 'EmailBlastController@store')->name('save-template');
        Route::put('/', 'EmailBlastController@update')->name('update-template');
        Route::get('/{id}/delete/', 'EmailBlastController@destroy')->name('delete-template');
    });

    Route::group(['prefix' => 'job-send-email'], function () {
        Route::get('/', 'JobBlastController@index')->name('list-job');
        Route::get('/create', 'JobBlastController@create')->name('create-job');
        Route::get('/{id}', 'JobBlastController@show')->name('show-job');
        Route::post('/', 'JobBlastController@store')->name('save-job');
        Route::put('/', 'JobBlastController@update')->name('update-jon');
        Route::get('/{id}/delete/', 'JobBlastController@destroy')->name('delete-job');

        Route::get('/{id}/resend', 'JobBlastController@resend')->name('resend-job');

    });

    Route::resource('config-email', 'ConfigEmailController');

    Route::get('/oauth/gmail/callback', function (){
        LaravelGmail::makeToken();
        return redirect()->to('/');
    });

    Route::group(['prefix' => 'gmail'], function () {

        Route::get('/login', function (){
            return LaravelGmail::redirect();
        })->name('gmail.login');

        Route::get('/logout', function (){
            LaravelGmail::logout(); //It returns exception if fails
            return redirect()->to('/home');
        })->name('gmail.logout');
                
        Route::get('/inbox', function () {
            // dd(request());
            $messages = LaravelGmail::message()->unread()->preload()->all();
            echo '<ul>';
            foreach ( $messages as $message ) {
                $body = $message->getHtmlBody();
                echo '<li>' . $subject = $message->getSubject() . '</li>';
            }
            echo '</ul>';
        })->name('gmail.inbox');

        Route::get('/compose', 'HomeController@composeGmail');
    
    });


});

// Route::get('/tes-mail', 'BlastEmailController@index');

// Route::get('/email', 'BlastEmailController@index');


// Route::get('/load-csv', 'BlastEmailController@loadCsv');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- script -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    @yield('styles')

    {{-- @trixassets --}}
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Contact
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('list-group-contact') }}">Contact Group</a>
                                <a class="dropdown-item" href="{{ route('list-contact') }}">List Contact</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Email Blast
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('config-email.index') }}">Email Config</a>
                                <a class="dropdown-item" href="{{ route('list-template') }}">Template</a>
                                <a class="dropdown-item" href="{{ route('list-job') }}">Job Send Email Blast</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Gmail API
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('gmail.login') }}">Login</a>
                                <a class="dropdown-item" href="{{ route('gmail.logout') }}">Logout</a>
                                <a class="dropdown-item" href="{{ route('gmail.inbox') }}">Inbox</a>
                            </div>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @include('flash-message')
            @yield('content')
        </main>
    </div>

    @yield('scripts')
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( '.ckeditor' );
    </script>
</body>
</html>